/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

/********************************************************************************************
 *     LEGAL DISCLAIMER
 *
 *     (Header of MediaTek Software/Firmware Release or Documentation)
 *
 *     BY OPENING OR USING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 *     THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE") RECEIVED
 *     FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON AN "AS-IS" BASIS
 *     ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED,
 *     INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR
 *     A PARTICULAR PURPOSE OR NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY
 *     WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 *     INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK
 *     ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
 *     NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S SPECIFICATION
 *     OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
 *
 *     BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE LIABILITY WITH
 *     RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION,
TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE
 *     FEES OR SERVICE CHARGE PAID BY BUYER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 *     THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE WITH THE LAWS
 *     OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF LAWS PRINCIPLES.
 ************************************************************************************************/
#ifndef _MTK_ASVD_H
#define _MTK_ASVD_H

#include "MTKAsvdType.h"
#include "MTKAsvdErrCode.h"

typedef enum
{
    ASVD_STATE_STANDBY,
    ASVD_STATE_INIT,
    ASVD_STATE_PROC,
    ASVD_STATE_READY,
    ASVD_STATE_IDLE,
    ASVD_STATE_MAX
}ASVD_STATE_ENUM;

typedef enum
{
    ASVD_FEATURE_BEGIN = 0,
    ASVD_FEATURE_GET_RESULT,
    ASVD_FEATURE_GET_STATUS,
    ASVD_FEATURE_SAVE_LOG,

    ASVD_FEATURE_SET_PROC_INFO,
    
    ASVD_FEATURE_GET_WORK_BUF_INFO,
    ASVD_FEATURE_SET_WORK_BUF_INFO,

    ASVD_FEATURE_MAX
}	ASVD_FEATURE_ENUM;

typedef enum
{
	ASVD_VIDEO_TYPE_AMBUGITY= 0,
	ASVD_VIDEO_TYPE_SAS,
	ASVD_VIDEO_TYPE_TAB,
	ASVD_VIDEO_TYPE_2D
}ASVD_VIDEO_TYPE_ENUM ;

typedef struct
{
	MUINT32 enable_tuning;		// 0: disable, 1: enable
	MFLOAT thr_sim_high; 
	MFLOAT thr_sim_low;
	MFLOAT thr_mid;
	MFLOAT thr_prb;

}ASVD_TUNING_PARA_STRUCT;

typedef struct
{
	MINT32  instance_count;
	MUINT32 input_width;
	MUINT32 input_height;
	ASVD_TUNING_PARA_STRUCT tuning_para;
} ASVD_SET_ENV_INFO_STRUCT, *P_ASVD_SET_ENV_INFO_STRUCT;


typedef struct
{
	ASVD_VIDEO_TYPE_ENUM video_type;
}ASVD_RESULT_STRUCT, *P_ASVD_RESULT_STRUCT;


typedef struct
{
    MUINT32 ext_mem_size;
    MUINT32 ext_mem_start_addr; //working buffer start address
}ASVD_SET_WORK_BUF_INFO_STRUCT, *P_ASVD_SET_WORK_BUF_INFO_STRUCT;

typedef struct
{
    MUINT32 source_image_addr;

}ASVD_SET_PROC_INFO_STRUCT, *P_ASVD_SET_PROC_INFO_STRUCT;

class MTKAsvd {
public:
    static MTKAsvd* createInstance();
    virtual void   destroyInstance() = 0;
    
    virtual ~MTKAsvd(){};
    // Process Control
    virtual MRESULT AsvdInit(void* InitInData);
    virtual MRESULT AsvdMain();		
    virtual MRESULT AsvdReset();
            
	// Feature Control        
	virtual MRESULT AsvdFeatureCtrl(MUINT32 FeatureID, void* pParaIn, void* pParaOut);
private:
};

//20120807
void InitMutex();
void DestroyMutex();

#endif