/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

/********************************************************************************************
 *     LEGAL DISCLAIMER 
 *
 *     (Header of MediaTek Software/Firmware Release or Documentation)
 *
 *     BY OPENING OR USING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES 
 *     THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE") RECEIVED 
 *     FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON AN "AS-IS" BASIS 
 *     ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED, 
 *     INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR 
 *     A PARTICULAR PURPOSE OR NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY 
 *     WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, 
 *     INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK 
 *     ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
 *     NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S SPECIFICATION 
 *     OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
 *     
 *     BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE LIABILITY WITH 
 *     RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION, 
TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE 
 *     FEES OR SERVICE CHARGE PAID BY BUYER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
 *     
 *     THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE WITH THE LAWS 
 *     OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF LAWS PRINCIPLES.  
 ************************************************************************************************/

#ifndef _MDPULT_H_
#define _MDPULT_H_

/****************************************
  			MDP ULT Test Case Catagory	
 ****************************************/

#define MDPULT_CAT_BITBLT
#define MDPULT_CAT_JPGDEC
#define MDPULT_CAT_JPEENC
//#define MDPULT_CAT_CAM



/****************************************
  	  		BitBlt Test Case
 ****************************************/

#define TEST_BIT_BLT_DIFF_SRC_SIZE_16_16            (1)
#define TEST_BIT_BLT_DIFF_SRC_SIZE_399_199          (2)
//#define TEST_BIT_BLT_DIFF_SRC_SIZE_5500_5500      (3)

#define TEST_BIT_BLT_DIFF_DST_SIZE_13_13            (4)
#define TEST_BIT_BLT_DIFF_DST_SIZE_720_480			(5)
#define TEST_BIT_BLT_DIFF_DST_SIZE_799_427		(6)

#define TEST_BIT_BLT_DIFF_SRC_FORMAT_RGB565 		(7)
#define TEST_BIT_BLT_DIFF_SRC_FORMAT_RGB888			(8)
#define TEST_BIT_BLT_DIFF_SRC_FORMAT_ARGB8888		(9)
#define TEST_BIT_BLT_DIFF_SRC_FORMAT_MTKYUV			(10)
#define TEST_BIT_BLT_DIFF_SRC_FORMAT_YUV420			(11)
#define TEST_BIT_BLT_DIFF_SRC_FORMAT_NV21			(12)
#define TEST_BIT_BLT_DIFF_SRC_FORMAT_YUYV422		(13)

#define TEST_BIT_BLT_DIFF_DST_FORMAT_RGB565			(14)
#define TEST_BIT_BLT_DIFF_DST_FORMAT_RGB888			(15)
#define TEST_BIT_BLT_DIFF_DST_FORMAT_ARGB8888		(16)
#define TEST_BIT_BLT_DIFF_DST_FORMAT_MTKYUV			(17)
#define TEST_BIT_BLT_DIFF_DST_FORMAT_YUV420			(18)
#define TEST_BIT_BLT_DIFF_DST_FORMAT_NV21			(19)
#define TEST_BIT_BLT_DIFF_DST_FORMAT_YUYV422		(20)

#define TEST_BIT_BLT_DIFF_ROTATE_90					(21)
#define TEST_BIT_BLT_DIFF_ROTATE_180				(22)
#define TEST_BIT_BLT_DIFF_ROTATE_270				(23)
#define TEST_BIT_BLT_DIFF_PITCH						(24)
#define TEST_BIT_BLT_DIFF_CLIP						(25)




/****************************************
  			Jpeg Eec Test Case
 ****************************************/
#define TEST_JPG_ENC_DIFF_SRC_SIZE_16_16 			(1)
#define TEST_JPG_ENC_DIFF_SRC_SIZE_399_199 			(2)
#define TEST_JPG_ENC_DIFF_SRC_SIZE_2048_2048 		(3)

#define TEST_JPG_ENC_DIFF_ENC_SIZE_16_16 			(4)
#define TEST_JPG_ENC_DIFF_ENC_SIZE_399_199 			(5)
#define TEST_JPG_ENC_DIFF_ENC_SIZE_256_8191	 		(6)

#define TEST_JPG_ENC_DIFF_SRC_FORMAT_RGB565 		(7)
#define TEST_JPG_ENC_DIFF_SRC_FORMAT_RGB888			(8)
#define TEST_JPG_ENC_DIFF_SRC_FORMAT_ARGB8888		(9)

#define TEST_JPG_ENC_DIFF_ENC_FORMAT_YUV422			(10)
#define TEST_JPG_ENC_DIFF_ENC_FORMAT_YUV411			(11)
#define TEST_JPG_ENC_DIFF_ENC_FORMAT_YUV420			(12)
#define TEST_JPG_ENC_DIFF_ENC_FORMAT_YUV400			(13)



/****************************************
  			Jpeg Dec Test Case
 ****************************************/

#define TEST_JPG_DEC_DIFF_SRC_SIZE_32_32			(1)
#define TEST_JPG_DEC_DIFF_SRC_SIZE_399_199			(2)
#define TEST_JPG_DEC_DIFF_SRC_SIZE_1600_1200		(3)
#define TEST_JPG_DEC_DIFF_SRC_SIZE_2592_1944		(4)
#define TEST_JPG_DEC_DIFF_SRC_SIZE_4096_4096		(5)
#define TEST_JPG_DEC_DIFF_SRC_SIZE_4096_8184		(6)
#define TEST_JPG_DEC_DIFF_DST_SIZE_16_16			(7)
#define TEST_JPG_DEC_DIFF_DST_SIZE_399_199			(8)
#define TEST_JPG_DEC_DIFF_DST_SIZE_928_928			(9)
#define TEST_JPG_DEC_DIFF_DST_FORMAT_RGB565			(10)
#define TEST_JPG_DEC_DIFF_DST_FORMAT_RGB888			(11)
#define TEST_JPG_DEC_DIFF_DST_FORMAT_ARGB8888		(12)

/****************************************
  			MDP ULT src & result path	
 ****************************************/
#define RESULT_PATH "/data/mdpult_result/"
#define SOURCE_PATH "/data/mdpult_source/"




/****************************************
  			MDP ULT	Resouce
 ****************************************/
#define MDPULT_RES_RGB565_16X16
#define MDPULT_RES_RGB565_399x199
#define MDPULT_RES_RGB565_80x80
#define MDPULT_RES_RGB565_256x256
#define MDPULT_RES_RGB565_405x405
#define MDPULT_RES_RGB888_80x80
#define MDPULT_RES_ARGB8888_80x80
#define MDPULT_RES_MTKYUV_352x288
#define MDPULT_RES_YUV420_240x416
#define MDPULT_RES_NV21_176x220
#define MDPULT_RES_YUYV422_104x60

#endif
