/********************************************************************************************
 *     LEGAL DISCLAIMER
 *
 *     (Header of MediaTek Software/Firmware Release or Documentation)
 *
 *     BY OPENING OR USING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 *     THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE") RECEIVED
 *     FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON AN "AS-IS" BASIS
 *     ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED,
 *     INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR
 *     A PARTICULAR PURPOSE OR NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY
 *     WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 *     INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK
 *     ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
 *     NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S SPECIFICATION
 *     OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
 *
 *     BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE LIABILITY WITH
 *     RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION,
TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE
 *     FEES OR SERVICE CHARGE PAID BY BUYER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 *     THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE WITH THE LAWS
 *     OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF LAWS PRINCIPLES.
 ************************************************************************************************/

#ifndef _FDVT_DRIVER_H_
#define _FDVT_DRIVER_H_

#include "./MTKDetection/MTKDetectionType.h"
#include "mt6573_fdvt.h"
#include "fdvtreg_mt6573.h"
#include "AppFDVT.h"


//#define MAX_FACE_NUM                            15
#define MAX_TRACKING_FACE_NUM 		        (15)
#define IMAGE_WIDTH				320
#define IMAGE_HEIGHT				240

#define FRAME_NUM_WITHOUT_FACE_TO_DO_ROTATION_SEARCH 60
#define FRAME_DETECT_DIVISION 1
#define GFD_BOUNDARY_OFF_RATIO 0

MINT32 halFDVT_OpenDriver();
MINT32 halFDVT_Uninit();
MINT32 halFDVT_StartHW(void* srcbuf);
MINT32 halFDVT_Wait_IRQ();
MINT32 halFDVT_PARA_SET(MUINT32* Adr,MUINT32* value,int num,FDVT_OPERATION_MODE_ENUM fd_state);
MINT32 halFDGetFaceResult(MUINT32* Adr,MUINT32* value,int num,MUINT32 &result);
MINT32 halDumpReg();

#endif
